import fs from "node:fs";
import path from "node:path";
import type { Config } from "../config.js";
import { daemonScriptPath } from "./launcher.js";
import { piPath } from "../util/fsx.js";

/**
 * pjsr/generated/adp.js — compiled into the daemon via #include. Pulls PixInsight's own
 * ImageSolver and AnnotateImage script libraries (absolute paths depend on the install dir,
 * and PJSR #include needs literal paths, so the file is generated at server start).
 */
export function writeGeneratedIncludes(cfg: Config): string {
  const daemon = daemonScriptPath();
  const genDir = path.join(path.dirname(daemon), "generated");
  fs.mkdirSync(genDir, { recursive: true });
  const out = path.join(genDir, "adp.js");
  const src = path.join(path.dirname(path.dirname(cfg.piExe)), "src", "scripts");
  const solver = path.join(src, "ImageSolver", "ImageSolver.js");
  const annotate = path.join(src, "AnnotateImage", "AnnotateImage.js");
  const lines: string[] = ["// GENERATED by pixinsight-mcp at server start — do not edit.", `// PixInsight scripts dir: ${src}`];
  if (cfg.includeAdpScripts !== false && fs.existsSync(solver)) {
    // AstronomicalCatalogs.js (shared by both libraries) expands the SETTINGS_MODULE macro at include time.
    lines.push('#define SETTINGS_MODULE "PIMCP"', "#define USE_SOLVER_LIBRARY true", `#include "${piPath(solver)}"`);
  } else lines.push("// ImageSolver not included (missing or includeAdpScripts=false)");
  if (cfg.includeAdpScripts !== false && fs.existsSync(annotate)) {
    lines.push("#define USE_ANNOTATE_LIBRARY true", `#include "${piPath(annotate)}"`);
  } else lines.push("// AnnotateImage not included");
  const text = lines.join("\n") + "\n";
  if (!fs.existsSync(out) || fs.readFileSync(out, "utf8") !== text) fs.writeFileSync(out, text, "utf8");
  return out;
}
